language: android
jdk: 
 - oraclejdk8

android:
  components:
   # Uncomment the lines below if you want to
   # use the latest revision of Android SDK Tools
   - platform-tools-24.0.3
   - tools

   # The BuildTools version used by your project
   - build-tools-24.0.3

   # The SDK version used to compile your project
   - android-22
   - add-on-google_apis-google-24
   - extra-android-support
   - 

script:
 - gradle build connectedCheck
