language: android
jdk: oraclejdk8
sudo: false
 
android:
  components:
    - platform-tools
    - tools
    - build-tools-24.0.3
    - android-22
    - android-24
    - sys-img-armeabi-v7a-android-22
    - extra-android-m2repository
    
licenses:
    - android-sdk-license-c81a61d9
    - android-sdk-license.*
    - android.*

before_script:
  # Create and start emulator
   - echo no | android create avd --force -n test -t android-22 --abi armeabi-v7a
   - emulator -avd test -no-skin -no-audio -no-window &
   - android-wait-for-emulator
   - adb shell input keyevent 82 &
   - echo y | android update sdk --no-ui --filter build-tools-25.0.0
   - echo y | android update sdk --no-ui --filter android-25

  
before_install:
  - "chmod +x ./gradlew"

script:
  - ./gradlew test --stacktrace
  #- ./gradlew sonarqube -Dsonar.host.url=http://smartr.cs.hm.edu:9000
  - ./gradlew clean assembleDebug jacocoTestDebugUnitTestReport sonarqube

