language: android
jdk: oraclejdk8

android:
  components:
   # Uncomment the lines below if you want to
   # use the latest revision of Android SDK Tools
   - platform-tools
   - tools

   # The BuildTools version used by your project
   - build-tools-24.0.3

   # The SDK version used to compile your project
   - android-22
   - android-24
   - add-on-google_apis-google-24
   - extra-android-support
   
licenses:
     - android-sdk-license-c81a61d9
     - android-sdk-license-.+
     
before_install:
     - "chmod +x ./gradlew"

script: ./gradlew build connectedCheck --stacktrace
